# Generated by Django 2.1.4 on 2019-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='y2',
            field=models.IntegerField(null=True),
        ),
    ]
