# Generated by Django 2.1.4 on 2019-05-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_element_y2'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='x2',
            field=models.IntegerField(null=True),
        ),
    ]
