# Generated by Django 2.1.4 on 2019-05-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_element_x2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='x2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='y2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
