# Generated by Django 2.1.4 on 2019-05-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190502_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Plan'),
        ),
    ]
