# Generated by Django 2.1.4 on 2019-05-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190502_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan'),
            preserve_default=False,
        ),
    ]
