# Generated by Django 2.1.4 on 2019-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190502_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paddingX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='paddingY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
