# Generated by Django 2.1.4 on 2019-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190507_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
