# Generated by Django 2.1.4 on 2019-05-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_element_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='type',
            new_name='wallType',
        ),
    ]
