# Generated by Django 2.1.4 on 2019-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190527_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='master_floor',
            new_name='masterFloor',
        ),
    ]
