# Generated by Django 2.1.4 on 2019-05-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190528_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundedElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('h', models.IntegerField()),
                ('hAntiClockWise', models.BooleanField()),
                ('eAntiClockWise', models.BooleanField()),
                ('wallType', models.CharField(blank=True, max_length=10, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='element',
            name='y2',
        ),
    ]
