# Generated by Django 2.1.4 on 2019-05-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190530_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundedelement',
            old_name='hAntiClockWise',
            new_name='convexityAntiClockWise',
        ),
    ]
