# Generated by Django 2.1.4 on 2019-05-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190530_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('floor', models.IntegerField()),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan')),
            ],
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='level',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='masterFloor',
            new_name='levelFromGroundFloor',
        ),
        migrations.AddField(
            model_name='floor',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
