# Generated by Django 2.1.4 on 2019-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190531_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
