# Generated by Django 2.1.4 on 2019-06-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_plate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='type',
            new_name='plateType',
        ),
    ]
