# Generated by Django 2.1.4 on 2019-06-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20190605_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plate',
            name='x0',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='y0',
        ),
        migrations.AddField(
            model_name='platepoint',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Plate'),
        ),
    ]
