# Generated by Django 2.1.4 on 2019-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_aperture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperture',
            name='center',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
