# Generated by Django 2.1.4 on 2019-06-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190617_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan'),
            preserve_default=False,
        ),
    ]
