# Generated by Django 2.1.4 on 2019-06-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20190619_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grillage',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point2', to='catalog.Point'),
        ),
    ]
