# Generated by Django 2.1.4 on 2019-06-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20190605_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aperture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling', models.CharField(max_length=20)),
                ('center', models.IntegerField()),
                ('r', models.IntegerField(blank=True, null=True)),
                ('L', models.IntegerField(blank=True, null=True)),
                ('H', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('l1', models.IntegerField(blank=True, null=True)),
                ('l2', models.IntegerField(blank=True, null=True)),
                ('ld', models.IntegerField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Element')),
            ],
        ),
    ]
