# Generated by Django 2.1.4 on 2019-06-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_aperture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='H',
            new_name='maxH',
        ),
        migrations.RenameField(
            model_name='aperture',
            old_name='L',
            new_name='maxL',
        ),
    ]
