# Generated by Django 2.1.4 on 2019-06-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190617_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='h',
            new_name='smallH',
        ),
    ]
