# Generated by Django 2.1.4 on 2019-06-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20190617_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='smallH',
            new_name='h',
        ),
    ]
