# Generated by Django 2.1.4 on 2019-06-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20190617_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='center',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='filling',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='l1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='l2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='ld',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='maxH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='maxL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='r',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
