# Generated by Django 2.1.4 on 2019-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_aperture_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='w',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
