# Generated by Django 2.1.4 on 2019-06-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_aperture_w'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundedelement',
            old_name='h',
            new_name='qwe',
        ),
    ]
