# Generated by Django 2.1.4 on 2019-06-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20190617_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='w',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='roundedelement',
            old_name='qwe',
            new_name='h',
        ),
    ]
